"""add username in users table

Revision ID: b28cd8266ddd
Revises: 06784cc203a6
Create Date: 2026-04-15 13:22:52.199558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b28cd8266ddd"
down_revision: Union[str, Sequence[str], None] = "06784cc203a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.String(length=32), nullable=False)
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_users_username"), "users", ["username"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.drop_column("users", "username")
    # ### end Alembic commands ###
